package com.sntax.class33;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

public class TaskException {
	 static List<Exception>str=new ArrayList();
	
	
	 public static List<Exception>getAllExceptions(){
		 
		 //1 object of exception type
//		 int [] array= {1,2,3};
//		 try {
//			 System.out.println(array[4]);
//		 }catch(ArrayIndexOutOfBoundsException aob) {
//			 List<Exception> exceptionList;
//			exceptionList.add(aob);
//		 }
//		//2 object of exception type
//		 try {
//			 Object ob=new Double(50);
//			 Integer i=(Integer);
//			 
//		 }
//		 
//	 
//	
//		 return  exceptionList();	
//	}
//
//	public static void main(String[] args) {
//		
//		List<Exception>list=getAllExceptions();
//		
//		Iterator<Exception >eit=list.iterator();
//		while(eit.hasNext()) {
//			String message=eit.next().getMessage();
//			System.out.println(message);
//		}
//		
//		
//		
//
//	}
//
//}
